#!/usr/bin/env python3
"""The TrustFirst mark, and the script that regenerates every file it appears in.

THE MARK

The letter T drawn as an upward arrow, in three pieces:

    wing    a parallelogram - the left half of the T's crossbar
    head    a right triangle - the right half of the crossbar, and the
            arrowhead. Its vertical edge faces the wing across a wedge that
            opens downwards, which is the counter that makes the T readable.
    stem    a parallelogram hanging off the head's point, leaning the same
            way, so the T's stem doubles as the arrow's shaft.

Every slanted edge in the mark runs at the same angle: 9 across for 7 down,
37.9 degrees off horizontal. Nothing else is slanted, and nothing is curved.
One module sets the rest - the crossbar is `h` deep, and a slanted edge
covers d = h * 9/7 horizontally while it falls h. The head's two legs are
exactly d by h, and the stem is exactly d wide.

WHY THE NUMBERS LOOK ARBITRARY

They are measured, not invented. `wing_top` and `stem_edge` are the two free
proportions; the values here are the ones the mark was drawn with.

REGENERATING

    python3 brand/mark.py

Rewrites the three SVGs. The PNGs are rasterised from those SVGs by a
browser (see rasterise() below) because nothing in requirements.txt renders
SVG; if Playwright is not installed the script writes the SVGs, says so, and
leaves the PNGs alone.
"""
import json
import os
import subprocess
import sys

RUN, FALL = 9.0, 7.0          # the one slant, used by every angled edge

# The shipped proportions.
H          = 119.0            # crossbar depth
WING_TOP   = 214.0            # width of the wing, measured along the top edge
STEM_EDGE  = 155.0            # length of the stem's two vertical edges
GAP        = 3.0              # hairline, so no two pieces share a pixel
BOX        = 680              # the mark's width inside the 1024 icon square
RADIUS     = 225              # corner radius of the icon square
DARK       = '#1a1a1a'
LIGHT      = '#ffffff'

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HEADER = (
    '<!-- TrustFirst mark: the letter T drawn as an upward arrow. Three pieces on one\n'
    '     slant of 9 across to 7 down - a parallelogram wing, a triangular head, and a\n'
    '     leaning stem. Generated by brand/mark.py; edit that, not this path. -->'
)


def pieces(h=H, wing_top=WING_TOP, stem_edge=STEM_EDGE, gap=GAP):
    """The three shapes, in a local space with the crossbar's top edge at y=0."""
    d = h * RUN / FALL
    g = gap / 2.0
    wing = [(-g - wing_top, 0.0), (-g, 0.0), (-g - d, h), (-g - d - wing_top, h)]
    head = [(g, 0.0), (g + d, 0.0), (g, h)]
    stem = [(-g, h + g), (-g, h + g + stem_edge),
            (-g - d, h + g + stem_edge + h), (-g - d, h + g + h)]
    return [wing, head, stem]


def path_data(box=BOX, cx=512.0, cy=512.0, **kw):
    """SVG path data, scaled so the mark spans `box` and centred on (cx, cy)."""
    P = pieces(**kw)
    xs = [p[0] for q in P for p in q]
    ys = [p[1] for q in P for p in q]
    s = box / max(max(xs) - min(xs), max(ys) - min(ys))
    mx, my = (max(xs) + min(xs)) / 2.0, (max(ys) + min(ys)) / 2.0

    def fmt(v):
        t = '%.3f' % v
        return t.rstrip('0').rstrip('.') if '.' in t else t

    out = []
    for q in P:
        pts = [((x - mx) * s + cx, (y - my) * s + cy) for x, y in q]
        out.append('M ' + ' L '.join('%s %s' % (fmt(x), fmt(y)) for x, y in pts) + ' Z')
    return ' '.join(out)


def icon_svg(fg, bg):
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">\n'
        + HEADER + '\n'
        '<rect width="1024" height="1024" rx="%d" fill="%s"/>'
        '<path d="%s" fill="%s"/></svg>\n' % (RADIUS, bg, path_data(), fg)
    )


SVGS = [
    ('landing/icon.svg',                LIGHT, DARK),
    ('core/static/core/icon-dark.svg',  LIGHT, DARK),
    ('core/static/core/icon-light.svg', DARK,  LIGHT),
]

# Each PNG is rasterised from one of the SVGs above at one size.
PNGS = (
    [('core/static/core/icon-%s-%d.png' % (k, s), 'core/static/core/icon-%s.svg' % k, s)
     for k in ('dark', 'light') for s in (180, 192, 512)]
    + [('core/static/core/logo.png', 'core/static/core/icon-dark.svg', 1024)]
)

RASTERISE_JS = r'''
const { chromium } = require('playwright');
const fs = require('fs');
(async () => {
  const jobs = JSON.parse(process.argv[2]);
  const exe = process.env.CHROMIUM_PATH || undefined;
  const b = await chromium.launch(exe ? { executablePath: exe } : {});
  for (const j of jobs) {
    const p = await b.newPage({ viewport: { width: j.size, height: j.size }, deviceScaleFactor: 1 });
    await p.setContent('<style>html,body{margin:0;background:transparent}svg{display:block}</style>'
      + fs.readFileSync(j.svg, 'utf8').replace(/width="\d+" height="\d+"/, `width="${j.size}" height="${j.size}"`));
    await p.waitForTimeout(100);
    await p.screenshot({ path: j.out, omitBackground: true });
    await p.close();
    console.log('  ' + j.out);
  }
  await b.close();
})();
'''


def rasterise(jobs):
    """Render the PNGs with headless Chromium. Returns False if it is not available."""
    import tempfile
    with tempfile.NamedTemporaryFile('w', suffix='.js', delete=False) as f:
        f.write(RASTERISE_JS)
        script = f.name
    try:
        subprocess.run(['node', script, json.dumps(jobs)], cwd=ROOT, check=True)
        return True
    except (OSError, subprocess.CalledProcessError) as exc:
        print('  skipped the PNGs: %s' % exc, file=sys.stderr)
        return False
    finally:
        os.unlink(script)


def splash_pieces():
    """The three pieces as separate paths, plus the offsets the splash flies
    them in from.

        python3 brand/mark.py --splash

    feed.js carries a copy of these in createSplashScreen. They are stable as
    long as the mark is, so they are pasted rather than loaded at runtime; print
    them with this and replace them by hand if the mark ever changes.
    """
    import math
    P = pieces()
    xs = [p[0] for q in P for p in q]
    ys = [p[1] for q in P for p in q]
    box = 760.0
    s = box / max(max(xs) - min(xs), max(ys) - min(ys))
    mx, my = (max(xs) + min(xs)) / 2.0, (max(ys) + min(ys)) / 2.0

    def fmt(v):
        t = '%.2f' % v
        return t.rstrip('0').rstrip('.') if '.' in t else t

    out = []
    for q in P:
        pts = [((x - mx) * s + 512, (y - my) * s + 512) for x, y in q]
        out.append('M ' + ' L '.join('%s %s' % (fmt(x), fmt(y)) for x, y in pts) + ' Z')

    # The shear axis itself: 9 across as it falls 7, pointing up and to the
    # right. Each piece starts this far out along it and slides home, so nothing
    # travels in a direction the mark does not already contain.
    length = math.hypot(RUN, FALL)
    ax, ay = RUN / length, -FALL / length
    dist = 460.0
    return out, [
        ('splashWing', -ax * dist,        -ay * dist),
        ('splashHead',  ax * dist,         ay * dist),
        ('splashStem', -ax * dist * 0.75, -ay * dist * 0.75),
    ]


def main():
    if '--splash' in sys.argv:
        paths, offs = splash_pieces()
        print('paths, for the <path d="..."> in createSplashScreen:')
        for name, d in zip(('wing', 'head', 'stem'), paths):
            print('  %-5s %s' % (name, d))
        print('\noffsets, for the translate() in each @keyframes tfPiece*:')
        for name, dx, dy in offs:
            print('  %-11s translate(%.1fpx, %.1fpx)' % (name, dx, dy))
        return
    print('SVG')
    for rel, fg, bg in SVGS:
        with open(os.path.join(ROOT, rel), 'w') as f:
            f.write(icon_svg(fg, bg))
        print('  ' + rel)
    print('PNG')
    rasterise([{'out': out, 'svg': svg, 'size': size} for out, svg, size in PNGS])


if __name__ == '__main__':
    main()
